# Liked Movies

## Genres

In [2]:
import pandas as pd

df = pd.read_csv('liked_movies_with_genres.csv')

df['genre'].str.split(', ').explode().value_counts()

genre
Drama              77
Crime              33
Comedy             30
Action             30
Science Fiction    30
Thriller           28
Adventure          23
Fantasy            20
Romance            19
Animation          18
Family             15
Mystery            11
History             4
TV Movie            2
Western             2
Horror              2
War                 2
Music               1
Name: count, dtype: int64

## Longest runtime

In [3]:
df.nlargest(5, 'runtime')

,name,year,genre,runtime,directors
29,The Wolf of Wall Street,2013,"Crime, Drama, Comedy",180,Martin Scorsese
67,Casino,1995,"Crime, Drama",179,Martin Scorsese
121,The Big Country,1958,"Drama, Western, Romance",167,William Wyler
35,The Dark Knight Rises,2012,"Action, Crime, Drama, Thriller",165,Christopher Nolan
63,Avatar,2009,"Action, Adventure, Fantasy, Science Fiction",162,James Cameron

## Shortest runtime

In [4]:
df.nsmallest(5, 'runtime')

,name,year,genre,runtime,directors
70,My Life as a Zucchini,2016,"Animation, Comedy, Drama",66,Claude Barras
104,Bambi,1942,"Animation, Drama, Family",69,David Hand
122,Cinderella,1950,"Family, Fantasy, Animation, Romance",74,"Hamilton Luske, Clyde Geronimi, Wilfred Jackson"
103,Alice in Wonderland,1951,"Animation, Family, Fantasy, Adventure",75,"Clyde Geronimi, Wilfred Jackson, Hamilton Luske"
101,Half Baked,1998,"Comedy, Crime",82,Tamra Davis

## Total logged runtime

In [5]:
total_minutes = df.runtime.sum()
print(f"{total_minutes/1440} days")

10.068055555555556 days